# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitUserManager < Formula
  desc "Cli tool to quickly change between git users"
  homepage "https://github.com/Sarrus1/git_user_manager"
  url "https://github.com/Sarrus1/git_user_manager/archive/0.1.0.tar.gz"
  sha256 "d1812de2cce6fd414476d9f546109c2d08676948062d425cbed0b81777b291c9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Sarrus1/git_user_manager/releases/download/0.1.0/git_user_manager-0.1.0-darwin-amd64.tar.gz"
      sha256 "fe9a4af5a47ab8b254c0a75a510c7f8fac8348f968573200c398677640885a7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Sarrus1/git_user_manager/releases/download/0.1.0/git_user_manager-0.1.0-linux-amd64.tar.gz"
      sha256 "c3d46cbe908ca4da85c897cf39d900563abd17ecefc514ceacc8124449f53a8a"
    end
  end

  def install
    bin.install "gum" => "gum"
  end
end
