# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SourcepawnStudio < Formula
  desc "Vscode extension for sourcepawn scripting"
  homepage "https://github.com/Sarrus1/sourcepawn-studio"
  url "https://github.com/Sarrus1/sourcepawn-studio/archive/refs/tags/v8.1.1.tar.gz"
  sha256 "93e67276e14f4304efa44c2b0f777f67bd2b981ae8e405e723e759763dc34b3c"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "sourcepawn-studio" => "sourcepawn-studio"
  end
end
