# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SourcepawnStudio < Formula
  desc "Vscode extension for sourcepawn scripting"
  homepage "https://github.com/Sarrus1/sourcepawn-studio"
  url "https://github.com/Sarrus1/sourcepawn-studio/archive/refs/tags/v8.1.5.tar.gz"
  sha256 "4e74fb17d7161ead9527264d268a7babef72cfdfdbacdc2c7177895ff5037a18"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "sourcepawn-studio" => "sourcepawn-studio"
  end
end
