# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SourcepawnStudio < Formula
  desc "Vscode extension for sourcepawn scripting"
  homepage "https://github.com/Sarrus1/sourcepawn-studio"
  url "https://github.com/Sarrus1/sourcepawn-studio/archive/refs/tags/v8.1.2.tar.gz"
  sha256 "a9a05f49c49958b283a29b55cd1a0a0a685b623047b9e76f08dcdc497a9a77aa"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "sourcepawn-studio" => "sourcepawn-studio"
  end
end
