# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SourcepawnVscode < Formula
  desc "Vscode extension for sourcepawn scripting"
  homepage "https://github.com/Sarrus1/sourcepawn-vscode"
  url "https://github.com/Sarrus1/sourcepawn-vscode/archive/refs/tags/v7.1.0.tar.gz"
  sha256 "25249073b2146f58039e86ba6726a7d734d827828513c07c703a6a3bd5c903b4"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "sourcepawn_lsp" => "sourcepawn_lsp"
  end
end
