# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SourcepawnVscode < Formula
  desc "Vscode extension for sourcepawn scripting"
  homepage "https://github.com/Sarrus1/sourcepawn-vscode"
  url "https://github.com/Sarrus1/sourcepawn-vscode/archive/v6.2.0.tar.gz"
  sha256 "26e44e5493db61f81ea83ee77f4ef1e62beafc33f818680d8a5b35db271132b8"
  license "GPL-3.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "sourcepawn_lsp" => "sourcepawn_lsp"
  end
end
